<?php

include_once '../DTO/libroPacientes_DTO.php';

$numero=$_POST['data']['num'];
$nombres=$_POST['data']['nombres'];
$id=$_POST['data']['id'];
$tipoId=$_POST['data']['tipoId'];
$ingresaTto=$_POST['data']['ingresaTto'];
$fechaGestionMedicamento=$_POST['data']['fechaGestionMedicamento'];
$fechaTAES=$_POST['data']['fechaTAES'];
$ano=$_POST['data']['ano'];
$ipsDiagnostica=$_POST['data']['ipsDiagnostica'];
$ipsContinua=$_POST['data']['ipsContinua'];
$Pais=$_POST['data']['Pais'];
$entidadTerritorial=$_POST['data']['entidadTerritorial'];
$municipioProcedencia=$_POST['data']['municipioProcedencia'];
$sexo=$_POST['data']['sexo'];
$edad=intval($_POST['data']['edad']);
$uMedida=$_POST['data']['uMedida'];
$pertenenciaEtnica=$_POST['data']['pertenenciaEtnica'];
$puebloIndigena=$_POST['data']['puebloIndigena'];
$sector=$_POST['data']['sector'];
$barrio=$_POST['data']['barrio'];
$comuna=$_POST['data']['comuna'];
$ocupacion=$_POST['data']['ocupacion'];
$EAPB=$_POST['data']['EAPB'];
$regimen=$_POST['data']['regimen'];
$ubicacionGeografica=$_POST['data']['ubicacionGeografica'];
$telefono=$_POST['data']['telefono'];
$direccion=$_POST['data']['direccion'];
$grupoPoblacional=$_POST['data']['grupoPoblacional'];
$municipioNotifica=$_POST['data']['municipioNotifica'];
$fechaInicioSintomas=$_POST['data']['fechaInicioSintomas'];
$fechaDiagnostico=$_POST['data']['fechaDiagnostico'];
$trimestre=$_POST['data']['trimestre'];
$tipoTB=$_POST['data']['tipoTB'];
$localizacionTB=$_POST['data']['localizacionTB'];
$condicionIngreso=$_POST['data']['condicionIngreso'];
$ClasificacionTB=$_POST['data']['ClasificacionTB'];
$otroosCriteriosMedicos=$_POST['data']['otroosCriteriosMedicos'];
$DiagnosticoBK=$_POST['data']['DiagnosticoBK'];
$fechaDiagnosticoBK=$_POST['data']['fechaDiagnosticoBK'];
$cultivoDiagnostico=$_POST['data']['cultivoDiagnostico'];
$fechacultivoDiagnostico=$_POST['data']['fechacultivoDiagnostico'];
$pruebaMolecular=$_POST['data']['pruebaMolecular'];
$fechaPruebaMolecular=$_POST['data']['fechaPruebaMolecular'];
$realizoAPVVIH=$_POST['data']['realizoAPVVIH'];
$realizoPruebaVIH=$_POST['data']['realizoPruebaVIH'];
$resultadoPruebaVIH=$_POST['data']['resultadoPruebaVIH'];
$FechaReporteVIH=$_POST['data']['FechaReporteVIH'];
$PruebaConfirmatoriaAcordeNormaVIH=$_POST['data']['PruebaConfirmatoriaAcordeNormaVIH'];
$fechaDXPrevioActualVIH=$_POST['data']['fechaDXPrevioActualVIH'];
$recibeTARVIH=$_POST['data']['recibeTARVIH'];
$recibeTtoPreventivoVIH=$_POST['data']['recibeTtoPreventivoVIH'];
$coinfeccionPrevioVIH=$_POST['data']['coinfeccionPrevioVIH'];
$diagnosticoPrevioVIH=$_POST['data']['diagnosticoPrevioVIH'];
$pruebasusceptibilidadFarmacoResitencia=$_POST['data']['pruebasusceptibilidadFarmacoResitencia'];
$fechaReportePSF=$_POST['data']['fechaReportePSF'];
$tipoFarmacoResistencia=$_POST['data']['tipoFarmacoResistencia'];
$resitenteA=$_POST['data']['resitenteA'];
$cooomorbilidad=$_POST['data']['cooomorbilidad'];
$observacionesDiagnostico=$_POST['data']['observacionesDiagnostico'];
$BK2Mes=$_POST['data']['BK2Mes'];
$fechaBk2=$_POST['data']['fechaBk2'];
$BK4Mes=$_POST['data']['BK4Mes'];
$fechaBk4=$_POST['data']['fechaBk4'];
$BK6Mes=$_POST['data']['BK6Mes'];
$fechaBk6=$_POST['data']['fechaBk6'];
$BK9Mes=$_POST['data']['BK9Mes'];
$fechaBk9=$_POST['data']['fechaBk9'];
$controlMedico2Mes=$_POST['data']['controlMedico2Mes'];
$fechaControlMedico2Mes=$_POST['data']['fechaControlMedico2Mes'];
$observacionesControlMedico2Mes=$_POST['data']['observacionesControlMedico2Mes'];
$controlMedico4Mes=$_POST['data']['controlMedico4Mes'];
$fechaControlMedico4Mes=$_POST['data']['fechaControlMedico4Mes'];
$observacionesControlMedico4Mes=$_POST['data']['observacionesControlMedico4Mes'];
$controlMedico6Mes=$_POST['data']['controlMedico6Mes'];
$fechaControlMedico6Mes=$_POST['data']['fechaControlMedico6Mes'];
$observacionesControlMedico6Mes=$_POST['data']['observacionesControlMedico6Mes'];
$controlEnfermeria1Mes=$_POST['data']['controlEnfermeria1Mes'];
$fechaControlEnfermeria1Mes=$_POST['data']['fechaControlEnfermeria1Mes'];
$observacionesControlEnfermeria1Mes=$_POST['data']['observacionesControlEnfermeria1Mes'];
$controlEnfermeria3Mes=$_POST['data']['controlEnfermeria3Mes'];
$fechaControlEnfermeria3Mes=$_POST['data']['fechaControlEnfermeria3Mes'];
$observacionesControlEnfermeria3Mes=$_POST['data']['observacionesControlEnfermeria3Mes'];
$controlEnfermeria5Mes=$_POST['data']['controlEnfermeria5Mes'];
$fechaControlEnfermeria5Mes=$_POST['data']['fechaControlEnfermeria5Mes'];
$observacionesControlEnfermeria5Mes=$_POST['data']['observacionesControlEnfermeria5Mes'];
$cultivoFinalTto=$_POST['data']['cultivoFinalTto'];
$fechaCultivoFinalTto=$_POST['data']['fechaCultivoFinalTto'];
$condicionEgreso=$_POST['data']['condicionEgreso'];
$fechaCondicionEgreso=$_POST['data']['fechaCondicionEgreso'];
$fechaFinalTto=$_POST['data']['fechaFinalTto'];
$observacionesControl=$_POST['data']['observacionesControl'];
$peso=$_POST['data']['peso'];
$talla=$_POST['data']['talla'];
$imc=$_POST['data']['imc'];
$semanaEpidemiologica=$_POST['data']['semanaEpidemiologica'];
$periodoEpidemiologico=$_POST['data']['periodoEpidemiologico'];
$programasivigila=$_POST['data']['programasivigila'];
$resultBKFinal=$_POST['data']['resultBKFinal'];

//print_r($_POST['data']);



$mngLP = new libroPacientes_DTO();
        
$data = $mngLP->actualizarPacienteLibroRegistro($numero, $nombres, $id, $tipoId, $ingresaTto, $fechaGestionMedicamento, $fechaTAES, $ano, $ipsDiagnostica, $ipsContinua, $Pais, $entidadTerritorial, $municipioProcedencia, $sexo, $edad, $uMedida, $pertenenciaEtnica, $puebloIndigena, $sector, $barrio, $comuna, $ocupacion, $EAPB, $regimen, $ubicacionGeografica, $telefono, $direccion, $grupoPoblacional, $municipioNotifica, $fechaInicioSintomas, $fechaDiagnostico, $trimestre, $tipoTB, $localizacionTB, $condicionIngreso, $ClasificacionTB, $otroosCriteriosMedicos, $DiagnosticoBK, $fechaDiagnosticoBK, $cultivoDiagnostico, $fechacultivoDiagnostico, $pruebaMolecular, $fechaPruebaMolecular, $realizoAPVVIH, $realizoPruebaVIH, $resultadoPruebaVIH, $FechaReporteVIH, $PruebaConfirmatoriaAcordeNormaVIH, $fechaDXPrevioActualVIH, $recibeTARVIH, $recibeTtoPreventivoVIH, $coinfeccionPrevioVIH, $diagnosticoPrevioVIH, $pruebasusceptibilidadFarmacoResitencia, $fechaReportePSF, $tipoFarmacoResistencia, $resitenteA, $cooomorbilidad, $observacionesDiagnostico, $BK2Mes, $fechaBk2, $BK4Mes, $fechaBk4, $BK6Mes, $fechaBk6, $BK9Mes, $fechaBk9, $controlMedico2Mes, $fechaControlMedico2Mes, $observacionesControlMedico2Mes, $controlMedico4Mes, $fechaControlMedico4Mes, $observacionesControlMedico4Mes, $controlMedico6Mes, $fechaControlMedico6Mes, $observacionesControlMedico6Mes, $controlEnfermeria1Mes, $fechaControlEnfermeria1Mes, $observacionesControlEnfermeria1Mes, $controlEnfermeria3Mes, $fechaControlEnfermeria3Mes, $observacionesControlEnfermeria3Mes, $controlEnfermeria5Mes, $fechaControlEnfermeria5Mes, $observacionesControlEnfermeria5Mes, $cultivoFinalTto, $fechaCultivoFinalTto, $condicionEgreso, $fechaCondicionEgreso, $fechaFinalTto, $observacionesControl, $peso, $talla, $imc, $semanaEpidemiologica, $periodoEpidemiologico, $programasivigila, $resultBKFinal);

echo json_encode($data);
