<?php
header("Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
header('Content-Disposition: attachment; filename=nombre_archivo.xlsx');

  
?>
<table border="1" cellpadding="2" cellspacing="0" width="100%"> 
    <caption>Tabla de pruebas</caption> 
    <tr> 
        <td style="background-color: green;color:white;">Datos</td> 
        <td style="color:gray;">Datos</td> 
        <td>Datos</td> 
    </tr>
</table>


